Support hot reload #125
COSCUP/COSCUP-Volunteer pull request #130
Opened 2023-03-09 09:15 UTC by orertrr

更改開發階段時建立 container 的方式與相關設定，並支援 hot reload

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #125

## What is the new behavior?

- 使用 bind mount 將檔案放入 container
- 使用 flask 內建的 WSGI server 代替 uwsgi 並加入 `--debug` 參數，使 python 程式碼變更後自動重跑
- uvicorn 加入 `--debug`  參數，使 `/api` 內的程式碼變更後自動重跑
- 開啟 `app.config['TEMPLATES_AUTO_RELOAD']`，使 templates 變更後重整瀏覽器可以下載到新的程式碼

**額外**
- 修改 docs site 後可直接執行 `docker compose run docs` 建立文件

## Other information

目前 main.py 與 setting.py 更改後 server 無法自動重跑，測試後發現如果 mount 單一檔案到 container 時才會發生此現象

2023-03-10 00:29 UTC, toomore commented
@orertrr 這個目前看起還很棒，不會有與正式環境衝突的問題，但發現一個問題是 CPU 會有升高的狀況，不確定是不是改成這樣因此（對於 docker 來說）監控檔案變化的數量太多造成。

或許可以參考[這裡的規格](https://docs.docker.com/compose/compose-file/#volumes) ，試試用 `ro`(read-only access) 或是 `nocopy` 的方式，觀察 CPU 的狀況！

2023-03-10 02:15 UTC, orertrr commented
OK，我再看一下

2023-03-10 10:24 UTC, orertrr commented
@toomore 有觀察到一個現象是，使用 flask 的內建伺服器時，`logs/apps/log.log` 的內容會暴增，有沒有可能是因為不斷寫入 log 導致 CPU 使用率升高？

目前來看是因為 `watchdog` 這個套件會一直探測到 log 被更改並不斷的寫入 log，才導致 log 內容暴增。

2023-03-17 10:01 UTC, toomore requested changes
@orertrr 再幫忙調整一下，感謝！

2023-03-17 12:04 UTC, orertrr commented on docs_dev/entrypoint.sh
我測試下面的設定後，結果會變成一個空的 `.git` 留在 `docs_dev` 裡面
```
tmpfs:
  - /app/docs_dev/.git
```

如果調整成下面這樣
```
volumes:
  - $PWD/.git:/app/.git
```
直接把現有的 `.git` 搬到 container 裡面會不會比較好？

2023-03-17 15:52 UTC, toomore requested changes
`docs_dev/.git` 有點難解。

2023-03-17 15:52 UTC, toomore commented on docker-compose.yml
> +      - $PWD/docs_dev:/app/docs_dev
稍微整理一下，在 `celery_worker` 不需要這兩行。

2023-03-17 15:52 UTC, toomore commented on docker-compose.yml
> +      - $PWD/docs_dev:/app/docs_dev
稍微整理一下，在 `apiapp` 底下不需要這一行。

2023-03-17 15:52 UTC, toomore commented on docker-compose.yml
> +      - $PWD/docs_dev:/app/docs_dev
稍微整理一下，在 `webapp` 底下不需要這兩行。

2023-03-17 15:52 UTC, toomore commented on docs_dev/entrypoint.sh
@orertrr 不不不， `docs_dev/.git` 是因為執行 [docs_dev/entrypoint.sh](https://github.com/COSCUP/COSCUP-Volunteer/pull/130/files/f480b607b3c1c85ce64fbeffd9e15559bd509ad4#diff-8ce1444ba7302bccfc40f2bd39ecff788cf2ee24d910a98144ff219ec0c667c4) 產生出來的，`docs_dev/.git` 他只是因為在跑開發環境時臨時需要用到。而 `docs_dev/.git` 與 `.git` 是不一樣的 `.git`，後者是整個專案原本的。

這題有點難解，目標是開發結束後不要出現 `docs_dev/.git`.

2023-03-18 01:21 UTC, orertrr commented
@toomore 

`docs_dev/.git` 那部分我在 `entrypoint.sh` 多加一個 `cleanup` function
當執行完時會刪除 `docs_dev/.git`

2023-03-18 03:18 UTC, toomore requested changes
好像剩這個修正就差不多了！我再多測試一下！！

2023-03-18 03:18 UTC, toomore commented on docker-compose.yml
>      entrypoint: ["poetry", "run", "celery", "-A", "celery_task.celery_main", "worker", "-B", "-l", "info", "-O", "fair", "-c", "4", "--logfile", "./log/log.log"]
@orertrr 找到一個沒修正到，幫忙改一下！`./log/log.log` -> `/var/log/workers/log.log`

2023-03-18 04:24 UTC, orertrr commented on docker-compose.yml
>      entrypoint: ["poetry", "run", "celery", "-A", "celery_task.celery_main", "worker", "-B", "-l", "info", "-O", "fair", "-c", "4", "--logfile", "./log/log.log"]
OK，修正好了

2023-03-18 15:54 UTC, merged