出款單合併、顯示 #116 #117 #118
COSCUP/COSCUP-Volunteer pull request #136
Opened 2023-04-29 05:08 UTC by ddio

## Pull request type

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

1. #116, 讓 API 支援建立出款單（dispense）
   1. 編輯出款單的部份，會在 #119 處理
2. #117, 讓 UI 支援建立出款單
   1. 在 `審核中` 畫面時，允許勾選申請單，顯示總計金額
       > ![螢幕快照 2023-04-29 12-56-36](https://user-images.githubusercontent.com/271157/235284361-a81197c2-f4e0-4450-b9e4-de2ea92f5fd6.png)
   2. 填寫出款日期後，即可建立出款單
      > ![螢幕快照 2023-04-29 12-57-53](https://user-images.githubusercontent.com/271157/235284381-a9af11ea-6e01-4228-bca4-4caa933240fa.png)
   4. 未免意外，若勾選的申請單，包含多個銀行帳戶時，將無法建立出款單
      > ![螢幕快照 2023-04-29 12-56-33](https://user-images.githubusercontent.com/271157/235284400-39c315bf-97fa-4148-81c6-e56425b37275.png)
3. #118, 在「出款中、已出款、已完成」的畫面中，改以出款單顯示
   >  ![螢幕快照 2023-04-29 13-00-10](https://user-images.githubusercontent.com/271157/235284436-83a3014e-dee7-4db5-af3a-7f023a0c324f.png)
   1. 為了向前相容，在沒有出款單時，就會顯示該狀態的申請單，讓 2022 以前的頁面，還可以如期顯示
      > ![螢幕快照 2023-04-29 13-02-27](https://user-images.githubusercontent.com/271157/235284490-4f67225b-e3d0-4840-81ea-c4a868d05f16.png)

## Other information

因為 expense 頁面漸趨複雜，所以進行了以下重構：

1. 將原本畫面裡的 table & modal 全都拆出去，方便重複使用
2. 將許多重複出現的 UI 元件，像是 invoice 、user 等等，全都做成 vue component ，方便重複使用
2. 導入 `/* html */` 語法，只要用 vscode + [es6-string-html](https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html)，就能讓目前的 vue component ，也能吃到 html highlight
3. 安裝 [buefy](https://buefy.org/) 的 JS ，但沒有安裝 css
   1. buefy 是 bulma 的 vue 套件，所以 css 和 bulma 相容
   1. 主要是為了方便實做 modal ，後來也有用在 table
   2. 因為 COSCUP 的 bulma 顏色設定和 buefy 不同，所以沒有加上 buefy css ，有些複雜元件（像是 b-datepicker），會無法使用

@toomore  可以看看有沒有什麼建議～

2023-04-29 05:09 UTC, ddio commented
@toomore  抱歉這個  PR 頗大，但為了怕影響到正式環境，所以出款單的部份，一直作到支援基本的顯示之後，才送 PR ～

2023-04-30 13:22 UTC, toomore requested changes
只有一個地方要修改，感謝！

2023-04-30 22:21 UTC, ddio commented on Dockerfile-app-dev
> -    ./view/dev.py \
Done! 抱歉整理後漏放回這個

2023-05-01 03:54 UTC, toomore approved these changes

2023-05-02 02:21 UTC, merged