#119, Allow edit dispense
COSCUP/COSCUP-Volunteer pull request #137
Opened 2023-04-29 14:32 UTC by ddio

## Pull request type

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

1. #119, 允許修改出款單的 `出款日期` 與 `出款階段`
   >  ![圖片](https://user-images.githubusercontent.com/271157/235308041-f7196544-3be6-4a6d-98b0-043bbc311a11.png)
1. #117, 允許從申請單 modal ，直接將單筆申請單轉為出款單
   > ![圖片](https://user-images.githubusercontent.com/271157/235308171-35f4731d-7cae-4813-90aa-50f742671288.png)
   - 順道在表格末增加了「編輯申請單」按鈕，加強互動提示
3. #119, 允許刪除出款單，當刪除後，會顯示警語，將請款單搬回「審核中」，改為刪除後，即無法復原
   >  ![圖片](https://user-images.githubusercontent.com/271157/235308088-4d3ed15f-26d7-4cf3-9a6d-2f61a8e13c32.png)
   - API 層也有做相同的檢查

## Other information

@toomore  ，因為我接下來幾天不會有進度，所以就先把後續的 PR 一起放上來了，這個 PR 實際上只有最後 7 個 commit 而已，等前一個 PR 進去了，會在 rebase

2023-04-30 13:33 UTC, toomore requested changes
幫我調整一些小地方，感謝！

2023-04-30 13:33 UTC, toomore commented on module/dispense.py
> +        for allowed_key in ['status', 'dispense_date', 'enable']:
`('status', 'dispense_date', 'enable')` 幫我改成 tuple

2023-04-30 13:33 UTC, toomore commented on view/dispense.py
> +def handle_update (data: dict[str, Any]) -> Response:
這裡調整成 `-> ResponseBase`，上面的 L14 就不用加入 `Response`
```suggestion
def handle_update (data: dict[str, Any]) -> ResponseBase:
```

2023-04-30 13:33 UTC, toomore commented on view/dispense.py
> +def by_project_index(pid: str) -> str | ResponseBase | Response:
調整 L47 這裡就不用加 `Response`
```suggestion
def by_project_index(pid: str) -> str | ResponseBase:
```

2023-04-30 22:22 UTC, ddio commented on view/dispense.py
> +def handle_update (data: dict[str, Any]) -> Response:
done!

2023-04-30 22:22 UTC, ddio commented on view/dispense.py
> +def by_project_index(pid: str) -> str | ResponseBase | Response:
感謝建議～

2023-04-30 22:22 UTC, ddio commented on module/dispense.py
> +        for allowed_key in ['status', 'dispense_date', 'enable']:
done!

2023-05-01 03:53 UTC, toomore approved these changes

2023-05-02 02:21 UTC, merged