instruction of ssl certificate verify failed
COSCUP/COSCUP-Volunteer pull request #89
Opened 2022-06-28 14:58 UTC by oceanchad

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Instruction of ssl verification issue when install Poetry.

2022-06-28 15:06 UTC, pan93412 requested changes

2022-06-28 15:06 UTC, pan93412 commented on docs_dev/docs/dev/beginners.md
> +If you got error like `'urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed'`, go check your python3 folder `/Applications/Python 3.10/` and click `Instal
簡單修了一下文法和語句：

```
When you encountered such an error like `'urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed'` on macOS, you can navigate to your Python 3 installation folder (such as `/Application/Python 3.10`) and run `Install Certificates.command`.
```

如果覺得不太好的話，也可以把它改得更好  ><

2022-06-29 01:37 UTC, pan93412 approved these changes

2022-06-29 06:48 UTC, toomore commented
Hi @oceanchad , we need signoff[1] the commit by following the DCO declaration. How to fix the problem please read the alert result here[2], thank you.

[1] https://volunteer.coscup.org/docs/dev/contribute-on-github/
[2] https://github.com/COSCUP/COSCUP-Volunteer/pull/89/checks?check_run_id=7095891856

2022-06-29 07:10 UTC, pan93412 commented
Let me help him to sign off correctly.

2022-06-29 07:16 UTC, pan93412 commented
cc @toomore

2022-09-17 03:08 UTC, closed without merging